#!/bin/bash


ACTION="$1"

shift
PACKAGE_LIST=$@

case $ACTION in

	getStatus)
		[ -e /opt/SoundShow/SoundShow.x86_64 ] && echo 0 || echo 1	
			
	;;

	
	installPackage)
		f=$(mktemp)
		fname=$(basename $f).zip
		/usr/share/zero-lliurex-soundshow/soundshow-downloader.py $f
		d=$(mktemp -d)
		mv $f ${d}/${fname}
		cd $d
		unzip $fname
		mv -v SoundShow /opt
		cp /usr/share/zero-lliurex-soundshow/app.soundshow.soundshow.desktop /usr/share/applications
	;;

	remove)
		
		echo "Removing files..."
		rm -frv /opt/SoundShow /usr/share/applications/app.soundshow.soundshow.desktop
	;;		
		
esac
exit 0
