Name=zero-lliurex-soundshow
Name[en]=Sound Show
Name[es]=Sound Show
Name[ca@valencia]=Sound Show
Name[ca_ES]=Sound Show
Comment= Advanced Soundboard for Live Performances
Comment[en]= Advanced Soundboard for Live Performances
Comment[es]= Mesa de sonido para actuaciones en directo
Comment[ca@valencia]= Taula de sò per a actuacions en directe
Comment[ca_ES]= Mesa de sonido para actuaciones en directo
Icon=zero-lliurex-soundshow
Category=Software
ScriptPath=zero-lliurex-soundshow.zmd
Using=pkexec
Service=False
Locks=zero-lliurex-soundshow
Groups=*;
Show=False
